version: '3'

services:
  api:
    build:
      context: .
    ports:
      - 443:443
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
    - ./prometheus/:/etc/prometheus/
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.config.file=/etc/prometheus/web.yml
    
  db:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - .env  
    volumes:
      - ./data:/data/db
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}"
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
